<?php

declare(strict_types=1);

namespace DealNews\SchemaOrg\Type;

/**
 * Report.
 *
 * A Report generated by governmental or non-governmental organization.
 *
 * @see https://schema.org/Report
 */
class Report extends Article {

    public const SCHEMA_TYPE = 'Report';

    /**
     * The number or other unique designator assigned to a Report by the publishing
     * organization.
     *
     * @var string|array|null
     *
     * @see https://schema.org/reportNumber
     */
    public string|array|null $reportNumber = null;
}
